### ISSUE TITLE
Issue with plot_cpdb2

### ISSUE THREAD

**Issue by rtoddler** [zktuong/ktplots#31]
Hi @zktuong,

Thank you for the great tool! I encountered an issue when using plot_cpdb2.
p <- plot_cpdb2(cell_type1 = 'cluster6|cluster8', cell_type2 = 'cluster0',
                scdata = sce, idents = "seurat_clusters", means = means, pvals = pvals, deconvoluted = decon, 
                desiredInteractions = list(c('cluster6', 'cluster0'), c('cluster8', 'cluster0')),
                node_group_colors = c("cluster0" = "#86bc86", "cluster6" = "#79706e", "cluster8" = "#ff7f0e"),
                keep_significant_only = TRUE, standard_scale = TRUE, remove_self = TRUE)

It returns "**Please check that plot_cpdb works first!**" 

so I ran the plot_cpdb and confirmed that it's working.
plot_cpdb(cell_type1 = 'cluster6|cluster8', cell_type2 = 'cluster0', scdata = Combined,
          idents = 'seurat_clusters', # column name where the cell ids are located in the metadata
          means = means, pvals = pvals, keep_significant_only = TRUE)

Do you know what's wrong with it and how to solve the problem?

Thanks!

**Comment by zktuong** [comment]
Hi, thanks for your interest in this package.

I suppose `sce` and `Combined` are the same object but just converted?

At the moment, the error is complaining that it can't plot because the input table after `plot_cpdb` is empty or malformed.

Can i ask you to send me a minimal zipped file that contains your `sce` (just subset to cluster0 6 and 8), `means`, `pvals`, and `decon` to kt16@sanger.ac.uk and I will try and see what's the issue.

**Comment by rtoddler** [comment]
Yes, I converted my seurat obj(Combined) to sce.
I have sent you the file. Thank you so much!

**Comment by zktuong** [comment]
Hey @rtoddler,

the issue is that the gene names in your object are mouse but the cellphonedb input is human symbols - so it couldn't find the right genes because they are different.

To illustrate this, `plot_cpdb2` is wanting to plot the interactions for:
```R
 [1] "CADM3"   "FGF10"   "JAM3"    "GLRA2"   "CCK"     "BDNF"    "GRN"     "COPA"    "NGFR"    "PDGFB"   "PTN"    
[12] "EFNA2"   "EFNA3"   "FGFR1"   "EFNB2"   "PLD2"    "EPHB2"   "EPHB6"   "EPHA4"   "EPHA8"   "NGF"     "GPR37"  
[23] "PLXNC1"  "KIT"     "GPR19"   "CADM1"   "CADM4"   "EPB41L1" "FAM3C"   "CCKBR"   "NTRK2"   "SORT1"   "LRP1"   
[34] "PTPRZ1"  "EPHA7"   "NCAM1"   "FGF9"    "ARF1"    "EFNB1"   "EFNB3"   "PSAP"    "SEMA7A"  "KITLG"   "ENHO"   
```

but your sce row/genes names are
```
 [1] "Xkr4"          "Rp1"           "Mrpl15"        "Lypla1"        "Tcea1"         "Rgs20"         "Gm16041"      
 [8] "Atp6v1h"       "Oprk1"         "Npbwr1"        "Rb1cc1"        "4732440D04Rik" "St18"          "Pcmtd1"       
[15] "Gm26901"       "Gm30414"       "Sntg1"         "Rrs1"          "Adhfe1"        "3110035E14Rik"
```

If you can provide the object as an SCE for the expression matrix you provided to cellphonedb, then it should work.

**Comment by zktuong** [comment]
this isn't an issue for the original `plot_cpdb` because it doesn't actually use the single-cell object other than the meta data. 

I will add a sanity check in the code to show this.
