### ISSUE TITLE
Issue with plot_cpdb2 

### ISSUE THREAD

**Issue by DocMonster77** [zktuong/ktplots#52]
Thank you for the great tool!However, I encountered an issue when using plot_cpdb2.
_Error in plot_cpdb(cell_type1 = cell_type1, cell_type2 = cell_type2, scdata = scdata,  : 
  Cannot find cell types.
The error is mismatch between cell_type1 and the single cell metadata (or idents provided)._

**Comment by zktuong** [comment]
Hi, thank you for the interest:
1) can i see your full command
2) can you confirm whether `plot_cpdb` itself works on your data set?
3) if you can show me the first 6 lines of your `meta.txt` and your `sce`'s `colData` showing the entries for the celltype annotation.

Also check if this is a similar issue with #48?

**Comment by DocMonster77** [comment]
Thank you for your timely answer, I am using data(kidneyimmune). First, based on your example data, I would like to run,I executed the following command
"library(SingleCellExperiment)
library(reticulate)
library(ktplots)
ad=import('anndata')

adata = ad$read_h5ad('rna.h5ad')
counts <- Matrix::t(adata$X)
row.names(counts) <- row.names(adata$var)
colnames(counts) <- row.names(adata$obs)
sce <- SingleCellExperiment(list(counts = counts), colData = adata$obs, rowData = adata$var)

means <- read.delim('out/means.txt', check.names = FALSE)
pvalues <- read.delim('out/pvalues.txt', check.names = FALSE)
deconvoluted <- read.delim('out/deconvoluted.txt', check.names = FALSE)
interaction_grouping <- read.delim('interactions_groups.txt')
# > head(interaction_grouping)
#     interaction       role
# 1 ALOX5_ALOX5AP Activating
# 2    ANXA1_FPR1 Inhibitory
# 3 BTLA_TNFRSF14 Inhibitory
# 4     CCL5_CCR5 Chemotaxis
# 5      CD2_CD58 Activating
# 6     CD28_CD86 Activating

test <- plot_cpdb2(cell_type1 = "CD4_Tem|CD4_Tcm|CD4_Treg", # same usage style as plot_cpdb
	cell_type2 = "cDC",
	idents = 'fine_clustering',
	split.by = 'treatment_group_1',
	scdata = sce,
	means = means,
	pvals = pvalues,
	deconvoluted = deconvoluted, # new options from here on specific to plot_cpdb2
	gene_symbol_mapping = 'index', # column name in rowData holding the actual gene symbols if the row names is ENSG Ids. Might be a bit buggy
	desiredInteractions = list(c('CD4_Tcm', 'cDC1'), c('CD4_Tcm', 'cDC2'), c('CD4_Tem', 'cDC1'), c('CD4_Tem', 'cDC2	'), c('CD4_Treg', 'cDC1'), c('CD4_Treg', 'cDC2')),
	interaction_grouping = interaction_grouping,
    edge_group_colors = c("Activating" = "#e15759", "Chemotaxis" = "#59a14f", "Inhibitory" = "#4e79a7", "   Intracellular trafficking" = "#9c755f", "DC_development" = "#B07aa1"),
    node_group_colors = c("CD4_Tcm" = "#86bc86", "CD4_Tem" = "#79706e", "CD4_Treg" = "#ff7f0e", "cDC1" = "#bcbd22"  ,"cDC2" = "#17becf"),
    keep_significant_only = TRUE,
    standard_scale = TRUE,
    remove_self = TRUE)“

However,  it does not work, So  I try to use the data(kidneyimmune), There is still an error. Can you provide "rna.h5ad" so that I can better understand the format of the whole command. thanks for your help

**Comment by zktuong** [comment]
Ah ok. So, that example does not work on `data(kidneyimmune)` because it's a different data set. The file is too big to send over (>2gb) so for now, i'll point out what went wrong.

1) the celltypes are not found in your dataset, nor in `kidneyimmune`:
`cell_type1 = "CD4_Tem|CD4_Tcm|CD4_Treg"`
`cell_type2 = "cDC"`
These have to be specific to your object, or in kidneyimmune's columns: `head(colData(kidneyimmune))`
2) the same celltypes have to be adjusted for:
`desiredInteractions = list(c('CD4_Tcm', 'cDC1'), c('CD4_Tcm', 'cDC2'), c('CD4_Tem', 'cDC1'), c('CD4_Tem', 'cDC2 '), c('CD4_Treg', 'cDC1'), c('CD4_Treg', 'cDC2')),`
3) and here as well:
`node_group_colors = c("CD4_Tcm" = "#86bc86", "CD4_Tem" = "#79706e", "CD4_Treg" = "#ff7f0e", "cDC1" = "#bcbd22" ,"cDC2" = "#17becf"),`
