### ISSUE TITLE
counts <- Matrix::t(adata$X) error

### ISSUE THREAD

**Issue by chrsyl** [zktuong/ktplots#67]
Using your transfer code from python to R  for the cellphonedb example file: normalised_log_counts.h5ad, I get following error: 
counts <- Matrix::t(adata$X)
Error in h(simpleError(msg, call)) :  error in evaluating the argument 'x' in selecting a method for function 't': invalid class “dgCMatrix” object: 'i' slot is not increasing within columns
> 
How to correct?

**Comment by zktuong** [comment]
Hi, if you are using anndata/python, maybe you can use [ktplotspy](https://www.github.com/zktuong/ktplotspy). 

Otherwise, in your `normalised_log_counts.h5ad`, is the the `.X` a `scipy.sparse.csr_matrix` class/object or is just a `numpy.ndarray` ? if it is the second one, save your `.h5ad` again after converting the format:

```python
from scipy.sparse import csr_matrix
adata.X = csr_matrix(adata.X)
adata.write_h5ad('new_norm.h5ad')
```

**Comment by chrsyl** [comment]
Helo,
Thanks for answer. I tried your advice on the cellphonedb sample file. But still no X appeared.
However, when I use library(zellkonverter) with readH5AD(), X appears and I can proceed.
Your library is excellent. Still I want to be able to do modifications :).
Best

**Comment by zktuong** [comment]
Oh ok great! I’ll look into updating the readme at some point.
